# Generated by Django 5.0.6 on 2024-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(),
        ),
    ]
